<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Nilogistic.BLL\Nilogistic.BLL.csproj" />
    <ProjectReference Include="..\Nilogistic.DAL\Nilogistic.DAL.csproj" />
    <ProjectReference Include="..\Nilogistic.Entity\Nilogistic.Entity.csproj" />
    <ProjectReference Include="..\Nilogistic.DTO\Nilogistic.DTO.csproj" />
    <ProjectReference Include="..\Nilogistic.Utility\Nilogistic.Utility.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>
</Project>
